---
- hosts: kube-master
  remote_user: root
  tasks:
  - include: kubelet.yaml

  - name: Initialize the master
    shell: kubeadm init --token mymymy.kubernetes --skip-preflight-checks 
    ignore_errors: yes

  - name: Install WaveNet network
    shell: kubectl apply -f https://git.io/weave-kube

  - name: Deploy Kube UI
    shell: kubectl create -f https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml
    ignore_errors: yes

  - name: Fetching admin file
    fetch:
      src: /etc/kubernetes/admin.conf
      dest: ~/.kube/config
      flat: yes

