---
- hosts: secondary-master
  vars:
    kube_node: undefined
  remote_user: root
  tasks:

  - name: Remove SSH file
    file: path=/root/.ssh/id_rsa state=absent

  - name: Creating pub SSH keys
    command: ssh-keygen -N '' -f /root/.ssh/id_rsa

  - name: Download pub key
    fetch: src=/root/.ssh/id_rsa.pub dest=/tmp/id_rsa.tmp flat=yes

  - name: Copy local key to kube-node1
    local_action: shell cat /tmp/id_rsa.tmp | ssh root@{{ kube_node1 }} "cat >> /root/.ssh/authorized_keys"

  - name: Copy local key to kube-node2
    local_action: shell cat /tmp/id_rsa.tmp | ssh root@{{ kube_node2 }} "cat >> /root/.ssh/authorized_keys"

  - name: Copy local key to kube-master2
    local_action: shell cat /tmp/id_rsa.tmp | ssh root@{{ kube_master1 }} "cat >> /root/.ssh/authorized_keys"

  - name: Copy local key to kube-master
    shell: cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys

  - name: Delete temporary files
    local_action: command rm -f /tmp/id_rsa.tmp


