---
- hosts: kube-node
  remote_user: root
  tasks:
  - include: kubelet.yaml

  - debug: msg="Master IP is {{ master_ip }}"

  - name: Initialize the node
    shell: kubeadm join --token mymymy.kubernetesssssss {{ master_ip }}:6443  --skip-preflight-checks
    ignore_errors: yes

